/**
 * Deno runtime integration using JsRuntime
 *
 * This module provides embedded JavaScript execution with custom ops for:
 * - Tool execution (suggest_command, read_scrollback)
 * - HTTP requests (op_fetch)
 *
 * Note: We use our own op_fetch implementation rather than deno_fetch because
 * deno's fetch extension requires many interconnected extensions (deno_webidl,
 * deno_web, deno_tls, deno_net) with complex version dependencies that are
 * difficult to manage without the full deno runtime and snapshot.
 */
use crate::deno::ops::{TerminaiOpState, create_terminai_extension};
use crate::deno::types::{ChatOptions, StreamMessage};
use crate::llm::tool_executor::ToolExecutor;
use anyhow::{Context, Result};
use deno_core::{
  Extension, JsRuntime, PollEventLoopOptions, RuntimeOptions, v8,
};
use futures::Stream;
use std::pin::Pin;
use std::sync::Arc;
use tokio::sync::mpsc;

/// The bundled agent JavaScript code.
/// This is generated by vite during the build process.
/// If the bundled agent is not available, we use a fallback.
#[cfg(has_bundled_agent)]
const AGENT_JS: &str = include_str!(env!("TERMINAI_AGENT_JS_PATH"));

#[cfg(not(has_bundled_agent))]
const AGENT_JS: &str = include_str!("fallback_agent.js");

/// Deno agent that can execute TypeScript code
pub struct DenoAgent {
  runtime: JsRuntime,
}

impl DenoAgent {
  /// Create a new Deno agent with the TypeScript module loaded
  pub async fn new(tool_executor: Arc<ToolExecutor>) -> Result<Self> {
    // Create runtime with deno extensions for native fetch support
    let extensions = create_runtime_extensions();

    let options = RuntimeOptions {
      extensions,
      ..Default::default()
    };

    // Create the runtime
    let mut runtime = JsRuntime::new(options);

    // Initialize op state with our tool executor and HTTP client
    {
      let http_client = reqwest::Client::builder()
        .user_agent("terminai-agent/1.0")
        .build()
        .context("Failed to create HTTP client")?;

      let op_state = TerminaiOpState {
        tool_executor: tool_executor.clone(),
        http_client,
      };
      runtime.op_state().borrow_mut().put(op_state);
    }

    // Execute bootstrap script to set up global APIs
    runtime
      .execute_script("<terminai:bootstrap>", BOOTSTRAP_JS.to_string())
      .context("Failed to execute bootstrap script")?;

    // Try to load the bundled agent, fall back to bootstrap if it fails
    #[cfg(has_bundled_agent)]
    {
      log::debug!("Loading bundled TypeScript agent");
      runtime
        .execute_script("<terminai:agent>", AGENT_JS.to_string())
        .context("Failed to execute bundled TypeScript agent")?;
    }

    #[cfg(not(has_bundled_agent))]
    {
      log::warn!("Bundled agent not available, using fallback");
      runtime
        .execute_script("<terminai:fallback>", AGENT_JS.to_string())
        .context("Failed to execute fallback bootstrap")?;
    }

    Ok(Self { runtime })
  }

  /// Call a JavaScript function and get the result
  async fn call_js_function<T: serde::de::DeserializeOwned>(
    &mut self,
    script: &str,
  ) -> Result<T> {
    // Execute the script that returns a promise
    let result_global = self
      .runtime
      .execute_script("<call>", script.to_string())
      .context("Failed to execute JavaScript")?;

    // Use with_event_loop_promise to resolve the promise while running the event loop
    // This returns when the promise resolves, without waiting for all pending ops
    let resolve_future = self.runtime.resolve(result_global);
    let resolved_global = self
      .runtime
      .with_event_loop_promise(resolve_future, PollEventLoopOptions::default())
      .await
      .context("Failed to resolve JavaScript promise")?;

    // Use the scope! macro to access the v8 scope and deserialize
    deno_core::scope!(scope, self.runtime);
    let local = v8::Local::new(scope, resolved_global);

    // Deserialize the v8 value to our Rust type
    let result: T = serde_v8::from_v8(scope, local)
      .context("Failed to deserialize JavaScript value")?;

    Ok(result)
  }

  /// Call a synchronous JavaScript function and get the result
  fn call_js_sync<T: serde::de::DeserializeOwned>(
    &mut self,
    script: &str,
  ) -> Result<T> {
    // Execute the script
    let result_global = self
      .runtime
      .execute_script("<call>", script.to_string())
      .context("Failed to execute JavaScript")?;

    // Use the scope! macro to access the v8 scope and deserialize
    deno_core::scope!(scope, self.runtime);
    let local = v8::Local::new(scope, result_global);

    // Deserialize the v8 value to our Rust type
    let result: T = serde_v8::from_v8(scope, local)
      .context("Failed to deserialize JavaScript value")?;

    Ok(result)
  }

  /// Start a chat stream with the agent
  pub async fn chat_stream(
    &mut self,
    options: ChatOptions,
  ) -> Result<Pin<Box<dyn Stream<Item = Result<StreamMessage>> + Send>>> {
    let options_json = serde_json::to_string(&options)
      .context("Failed to serialize chat options")?;

    // Call the chatStream function which returns an array of messages
    let script = format!(
      r#"
(async () => {{
    const options = {};
    try {{
        const messages = await globalThis.chatStream(options);
        return messages;
    }} catch (error) {{
        return [{{
            type: "result",
            isError: true,
            errors: [error.message || String(error)]
        }}];
    }}
}})()
"#,
      options_json
    );

    let messages: Vec<StreamMessage> = self
      .call_js_function(&script)
      .await
      .context("Failed to execute chat stream")?;

    // Convert Vec to Stream
    let (tx, rx) = mpsc::unbounded_channel();
    for msg in messages {
      let _ = tx.send(Ok(msg));
    }
    drop(tx);

    Ok(Box::pin(
      tokio_stream::wrappers::UnboundedReceiverStream::new(rx),
    ))
  }

  /// Test function to verify the agent works
  pub async fn test(&mut self) -> Result<String> {
    let script = r#"
(async () => {
    return await globalThis.testAgent();
})()
"#;

    self
      .call_js_function(script)
      .await
      .context("Failed to execute test")
  }

  /// Echo function for testing basic interop
  pub fn echo(&mut self, message: &str) -> Result<String> {
    let message_json = serde_json::to_string(message)?;
    let script = format!("globalThis.echo({})", message_json);
    self.call_js_sync(&script)
  }

  /// Add function for testing numeric interop
  pub fn add(&mut self, a: f64, b: f64) -> Result<f64> {
    let script = format!("globalThis.add({}, {})", a, b);
    self.call_js_sync(&script)
  }

  /// Check if the agent module is loaded
  pub fn is_loaded(&mut self) -> bool {
    let script = "globalThis.terminai?.isLoaded === true";
    self.call_js_sync::<bool>(script).unwrap_or(false)
  }

  /// Get the agent version
  pub fn version(&mut self) -> Result<String> {
    let script = "globalThis.terminai?.version || 'unknown'";
    self.call_js_sync(script)
  }
}

/// Bootstrap JavaScript to set up global APIs
/// This sets up the fetch API and other web APIs from deno extensions
const BOOTSTRAP_JS: &str = r#"
// Set up globalThis for web compatibility
globalThis.console = globalThis.console || {
  log: (...args) => { Deno.core.print(args.map(String).join(' ') + '\n'); },
  error: (...args) => { Deno.core.print('[ERROR] ' + args.map(String).join(' ') + '\n'); },
  warn: (...args) => { Deno.core.print('[WARN] ' + args.map(String).join(' ') + '\n'); },
  info: (...args) => { Deno.core.print('[INFO] ' + args.map(String).join(' ') + '\n'); },
  debug: (...args) => { Deno.core.print('[DEBUG] ' + args.map(String).join(' ') + '\n'); },
};

// Termin.AI namespace
globalThis.terminai = {
  version: '1.0.0',
  isLoaded: true,
};

// Simple test functions
globalThis.echo = (msg) => 'Echo: ' + msg;
globalThis.add = (a, b) => a + b;
"#;

/// Create the runtime extensions
fn create_runtime_extensions() -> Vec<Extension> {
  vec![
    // Our custom extension with tool ops (including op_fetch)
    create_terminai_extension(),
  ]
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::command::{CommandExecutor, SafetyValidator};
  use crate::llm::tool_executor::ToolExecutionContext;
  use std::sync::Arc;
  use tokio::sync::Mutex;

  fn create_test_tool_executor() -> Arc<ToolExecutor> {
    let context = ToolExecutionContext {
      vt_parser: None,
      command_suggestions: Arc::new(Mutex::new(Vec::new())),
      command_executor: CommandExecutor::new(),
      safety_validator: SafetyValidator::new(),
    };
    Arc::new(ToolExecutor::new(context))
  }

  #[tokio::test]
  async fn test_deno_agent_creation() {
    let tool_executor = create_test_tool_executor();

    let result = DenoAgent::new(tool_executor).await;
    assert!(
      result.is_ok(),
      "Failed to create Deno agent: {:?}",
      result.err()
    );
  }

  #[tokio::test]
  async fn test_deno_agent_is_loaded() {
    let tool_executor = create_test_tool_executor();
    let mut agent = DenoAgent::new(tool_executor).await.unwrap();

    assert!(agent.is_loaded(), "Agent should be loaded");
  }

  #[tokio::test]
  async fn test_deno_agent_version() {
    let tool_executor = create_test_tool_executor();
    let mut agent = DenoAgent::new(tool_executor).await.unwrap();

    let version = agent.version();
    assert!(
      version.is_ok(),
      "Failed to get version: {:?}",
      version.err()
    );
    println!("Agent version: {}", version.unwrap());
  }

  #[tokio::test]
  async fn test_deno_agent_echo() {
    let tool_executor = create_test_tool_executor();
    let mut agent = DenoAgent::new(tool_executor).await.unwrap();

    let result = agent.echo("Hello, World!");
    assert!(result.is_ok(), "Echo failed: {:?}", result.err());
    assert_eq!(result.unwrap(), "Echo: Hello, World!");
  }

  #[tokio::test]
  async fn test_deno_agent_add() {
    let tool_executor = create_test_tool_executor();
    let mut agent = DenoAgent::new(tool_executor).await.unwrap();

    let result = agent.add(2.0, 3.0);
    assert!(result.is_ok(), "Add failed: {:?}", result.err());
    assert_eq!(result.unwrap(), 5.0);
  }

  #[tokio::test]
  async fn test_deno_agent_test_function() {
    let tool_executor = create_test_tool_executor();
    let mut agent = DenoAgent::new(tool_executor).await.unwrap();

    let result = agent.test().await;
    assert!(result.is_ok(), "Test function failed: {:?}", result.err());
    println!("Test result: {}", result.unwrap());
  }

  #[tokio::test]
  async fn test_deno_agent_chat_stream() {
    let tool_executor = create_test_tool_executor();
    let mut agent = DenoAgent::new(tool_executor).await.unwrap();

    let options = ChatOptions {
      message: "Hello".to_string(),
      model: "claude-sonnet-4-5".to_string(),
      provider: "anthropic".to_string(),
      api_key: None, // No API key, should get an error
      system_prompt: None,
      terminal_context: None,
      max_turns: None,
      max_budget_usd: None,
    };

    let result = agent.chat_stream(options).await;
    assert!(result.is_ok(), "Chat stream failed: {:?}", result.err());

    // Collect messages
    use futures::StreamExt;
    let stream = result.unwrap();
    let messages: Vec<_> = stream.collect().await;

    assert!(!messages.is_empty(), "Should receive at least one message");
    println!("Received {} messages", messages.len());

    // The last message should be a result (possibly an error since no API key)
    if let Some(Ok(last_msg)) = messages.last() {
      assert!(last_msg.is_result(), "Last message should be a result");
    }
  }
}
